USE QUIZDUELL;

CREATE OR REPLACE TABLE USER (
    USER_ID INTEGER AUTO_INCREMENT,
    USERNAME VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR (64) NOT NULL CHECK ( LENGTH(PASSWORD) >= 8 ),
    HIGHSCORE INTEGER,
    AVATAR_ID INTEGER NOT NULL,
    LEVEL INTEGER NOT NULL,
    EXP INTEGER,
    WINS INTEGER,
    CONCURRENT_WINS INTEGER,
    PERFECT WINS INTEGER,
    LOSES INTEGER,

    PRIMARY KEY (USER_ID)
);