CREATE OR REPLACE TABLE USER_ACHIEVEMENT (
    USER_ID INTEGER,
    ACHIEVEMENT_ID INTEGER,
    
    PRIMARY KEY (USER_ID, ACHIEVEMENT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (ACHIEVEMENT_ID) REFERENCES ACHIEVEMENT(ACHIEVEMENT_ID)
);