USE QUIZDUELL;

CREATE OR REPLACE TABLE QUESTION (
    QUESTION_ID INTEGER,
    QUESTION VARCHAR (255) NOT NULL,
    RIGHT_ANSWER VARCHAR (255) NOT NULL,
    FALSE_ANSWER1 VARCHAR (255) NOT NULL,
    FALASE_ANSWER2 VARCHAR (255) NOT NULL,
    FALSE_ANSWER3 VARCHAR (255) NOT NULL,
    CATEGORY_ID INTEGER NOT NULL,

    PRIMARY KEY (QUESTION_ID)

);