USE QUIZDUELL;

CREATE OR REPLACE TABLE ACHIEVEMENT (
    ACHIEVEMENT_ID INTEGER AUTO_INCREMENT,
    ACHIEVEMENT_NAME VARCHAR(255) NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,   

    PRIMARY KEY (ACHIEVEMENT_ID)
);