USE quizduell;

ALTER TABLE USER ADD CONSTRAINT USER_AVATARID_AVATAR_AVATARID
    FOREIGN KEY (AVATAR_ID) REFERENCES AVATAR(AVATAR_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;

ALTER TABLE BELONG ADD CONSTRAINT BELONG_QUESTIONID_QUESTION_QUESTIONID
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(QUESTION_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;

ALTER TABLE BELONG ADD CONSTRAINT BELONG_GAMEID_GAME_GAMEID
    FOREIGN KEY (GAME_ID) REFERENCES GAME(GAME_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;

ALTER TABLE QUESTION ADD CONSTRAINT QUESTION_CATEGORYID_CATEGORY_CATEGORYID
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;


ALTER TABLE GAME ADD CONSTRAINT GAME_CATEGORYID_CATEGORY_CATEGORYID
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;