USE QUIZDUELL;

ALTER TABLE USER ADD CONSTRAINT USER_AVATARID_AVATAR_AVATARID
    FOREIGN KEY (AVATAR_ID) REFERENCES AVATAR(AVATAR_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;

ALTER TABLE QUESTION ADD CONSTRAINT QUESTION_CATEGORYID_CATEGORY_CATEGORYID
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;
