USE QUIZDUELL;

SELECT GAME_ID, USERNAME, CATEGORY FROM GAME
    JOIN USER U on GAME.USER_ID = U.USER_ID
    JOIN CATEGORY C on GAME.CATEGORY_ID = C.CATEGORY_ID;

SELECT QUESTION, CATEGORY FROM QUESTION JOIN CATEGORY C on C.CATEGORY_ID = QUESTION.CATEGORY_ID;

SELECT GAME_ID, USERNAME, QUESTION FROM GAME
    JOIN CATEGORY C on GAME.CATEGORY_ID = C.CATEGORY_ID
    JOIN USER U on GAME.USER_ID = U.USER_ID
    JOIN QUESTION Q on Q.QUESTION_ID = QUESTION_ID WHERE GAME_ID = 100;

SELECT USERNAME FROM USER WHERE HIGHSCORE > 100;

SELECT QUESTION_ID, QUESTION, CATEGORY FROM QUESTION JOIN CATEGORY C on C.CATEGORY_ID = QUESTION.CATEGORY_ID;

SELECT GAME_ID, USERNAME, CATEGORY FROM GAME JOIN USER U on GAME.USER_ID = U.USER_ID
                                   JOIN CATEGORY C on GAME.CATEGORY_ID = C.CATEGORY_ID
                                   WHERE CATEGORY = 'INFORMATIK';